### ISSUE TITLE
怎么登陆不了啊？？

### ISSUE THREAD

**Issue by divce** [HuiJa/bicycleSharingServer#1]

**Comment by huija** [comment]
账号密码都是admin
本地安装具体账号密码看sql插入为准

**Comment by FabbyBlaire** [comment]
登陆账号密码不论写啥都是跳到500.jsp，登录超时

**Comment by huija** [comment]
> 登陆账号密码不论写啥都是跳到500.jsp，登录超时

参考下这里面, 改下拦截器, 具体看你自己war包本地部署的url是怎样的.
https://github.com/huija/bicycleSharingServer/commit/0b5379b5dceed16f6af4ddae580247985d731306

不推荐搞ssm了, 直接上spring boot吧 ( •̀ ω •́ )✧ , 有什么问题, 直接邮件我吧, 这个项目war包部署应该没啥问题的

**Comment by FabbyBlaire** [comment]
太感谢了！后续有问题再来请教您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huija/bicycleSharingServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月7日(星期五) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huija/bicycleSharingServer] 怎么登陆不了啊？？ (#1)





  
登陆账号密码不论写啥都是跳到500.jsp，登录超时
  
参考下这里面, 改下拦截器, 具体看你自己war包本地部署的url是怎样的.
 0b5379b
 
不推荐搞ssm了, 直接上spring boot吧 ( •̀ ω •́ )✧ , 有什么问题, 直接邮件我吧, 这个项目war包部署应该没啥问题的
